# Generated by Django 3.2.4 on 2021-06-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_management_app', '0002_alter_feedbackstaffs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstaffs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
