# Generated by Django 3.2.4 on 2021-06-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_management_app', '0005_notificationstaffs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationStaffs',
        ),
    ]
